image:
  - Visual Studio 2017
  - Ubuntu1804

assembly_info:
  patch: false

configuration: Release

platform: Any CPU

services:
  - mysql

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  'Lidarr:Database': 'server=localhost;user id=root;password=Password12!; database=lidarrupdate;CharSet=utf8mb4'
  'Lidarr:DataDirectory': $(HOME)

# Install .NET Core SDK 1.0 rc4 build 004771
init:
  - ps: gci "env:"

build_script:
  - ps: dotnet restore --no-cache
  - ps: dotnet build .\LidarrAPI\LidarrAPI.csproj -c Release
  - ps: dotnet ef database update --project LidarrAPI --startup-project LidarrAPI

artifacts:
  - path: '.\LidarrAPI\bin\Any CPU\Release\netcoreapp2.1\LidarrAPI.dll'
