version: '3'
services:
    mysql:
        build: docker-services/mysql/.

        environment:
            - MYSQL_ROOT_PASSWORD=root

        ports:
            - "3306:3306"

    lidarrupdate:
        build: .

        ports:
            - "5000:5000"

        links:
            - mysql

        environment:
            - DataDirectory=/data
            - Database="server=mysql;user id=root;password=root;database=lidarrupdate;CharSet=utf8mb4"
            - ApiKey=
            - ASPNETCORE_URLS=http://0.0.0.0:5000

        volumes:
            - ./lidarrupdate-data:/data