version: '3'
services:
    mysql:
        build: docker-services/mysql/.
        ## For Environment Variables, please see the Dockerfile in the mysql FOLDER, they weren't sending at the right spot for the scripts from here

    lidarrupdate:
        build: .

        ports:
            - "5000:5000"

        links:
            - mysql

        environment:
            - DataDirectory=/data
            - Database=server=mysql;user id=root;password=root;database=lidarrupdate;CharSet=utf8mb4
            - ApiKey=
            - ASPNETCORE_URLS=http://0.0.0.0:5000

        volumes:
            - ./lidarrupdate-data:/data